"""create puntos_interes table

Revision ID: aae43ff21c50
Revises: 05bac4828637
Create Date: 2026-02-18 12:17:33.959183

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae43ff21c50'
down_revision: Union[str, None] = '05bac4828637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('puntos_interes',
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_puntos_interes_geom', 'puntos_interes', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_puntos_interes_osm_id'), 'puntos_interes', ['osm_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_puntos_interes_osm_id'), table_name='puntos_interes')
    op.drop_index('idx_puntos_interes_geom', table_name='puntos_interes', postgresql_using='gist')
    op.drop_table('puntos_interes')
    # ### end Alembic commands ###
