[program:app_example]
command=/home/erpnext/.services/app_example/venv/bin/gunicorn app.main:app -c /home/erpnext/.services/app_example/deploy/scripts/gunicorn_conf.py
directory=/home/erpnext/.services/app_example
user=erpnext
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/erpnext/.services/app_example/logs/app_example.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=PATH="/home/erpnext/.services/app_example/venv/bin",APP_ENV="development"
